name: woundwise
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  camera: ^0.11.0
  google_maps_flutter: ^2.6.1
  country_code_picker: ^3.0.0
  shared_preferences: ^2.2.3
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  image: ^4.1.7
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6
  flutter_carousel_intro: ^1.0.11
  provider: ^6.1.2
  pinput: ^5.0.0
  fluttertoast: ^8.2.6
  numberpicker: ^2.1.2
  http_parser: ^4.0.2
  syncfusion_flutter_pdfviewer: ^24.2.8
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  pdf: ^3.11.0
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name:

flutter:
  assets:
    - assets/
    - assets/pdf/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-Thin.ttf


  uses-material-design: true
